export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const RESTORE_TOKEN = 'RESTORE_TOKEN';
export const LOGOUT_USER = 'LOGOUT_USER';

export const SALES_BEGIN = 'SALES_BEGIN';
export const SALES_SUCCESS = 'SALES_SUCCESS';
export const SALES_ERROR = 'SALES_ERROR';

export const QUORDER_BEGIN = 'QUORDER_BEGIN';
export const QUORDER_SUCCESS = 'QUORDER_SUCCESS';
export const QUORDER_ERROR = 'QUORDER_ERROR';

export const PRODUCTION_BEGIN = 'PRODUCTION_BEGIN';
export const PRODUCTION_SUCCESS = 'PRODUCTION_SUCCESS';
export const PRODUCTION_ERROR = 'PRODUCTION_ERROR';
export const CLEAR_DATA = 'CLEAR_DATA';

export const CODE_BEGIN = 'CODE_BEGIN';
export const CODE_SUCCESS = 'CODE_SUCCESS';
export const CODE_ERROR = 'CODE_ERROR';

export const OVERDUE_BEGIN = 'OVERDUE_BEGIN';
export const OVERDUE_SUCCESS = 'OVERDUE_SUCCESS';
export const OVERDUE_ERROR = 'OVERDUE_ERROR';

export const TADA_LIST_BEGIN = 'TADA_LIST_BEGIN';
export const TADA_LIST_SUCCESS = 'TADA_LIST_SUCCESS';
export const TADA_LIST_ERROR = 'TADA_LIST_ERROR';

export const TADA_DELETE_BEGIN = 'TADA_DELETE_BEGIN';
export const TADA_DELETE_SUCCESS = 'TADA_DELETE_SUCCESS';
export const TADA_DELETET_ERROR = 'TADA_DELETET_ERROR';

export const EXPENSE_BEGIN = 'EXPENSE_BEGIN';
export const EXPENSE_SUCCESS = 'EXPENSE_SUCCESS';
export const EXPENSE_ERROR = 'EXPENSE_ERROR';

export const ADD_TADA_BEGIN = 'ADD_TADA_BEGIN';
export const ADD_TADA_SUCCESS = 'ADD_TADA_SUCCESS';
export const ADD_TADA_ERROR = 'ADD_TADA_ERROR';

export const UPDATE_TADA_BEGIN = 'UPDATE_TADA_BEGIN';
export const UPDATE_TADA_SUCCESS = 'UPDATE_TADA_SUCCESS';
export const UPDATE_TADA_ERROR = 'UPDATE_TADA_ERROR';

export const GET_LEAD_BEGIN = 'GET_LEAD_BEGIN';
export const GET_LEAD_SUCCESS = 'GET_LEAD_SUCCESS';
export const GET_LEAD_ERROR = 'GET_LEAD_ERROR';

export const GET_SALESPERSON_SUCCESS = 'GET_SALESPERSON_SUCCESS';

export const DELETE_LEAD_BEGIN = 'DELETE_LEAD_BEGIN';
export const DELETE_LEAD_SUCCESS = 'DELETE_LEAD_SUCCESS';
export const DELETE_LEAD_ERROR = 'DELETE_LEAD_ERROR';

export const ASSIGN_LEAD_BEGIN = 'ASSIGN_LEAD_BEGIN';
export const ASSIGN_LEAD_SUCCESS = 'ASSIGN_LEAD_SUCCESS';
export const ASSIGN_LEAD_ERROR = 'ASSIGN_LEAD_ERROR';

export const COLLAB_LEAD_BEGIN = 'COLLAB_LEAD_BEGIN';
export const COLLAB_LEAD_SUCCESS = 'COLLAB_LEAD_SUCCESS';
export const COLLAB_LEAD_ERROR = 'COLLAB_LEAD_ERROR';

export const FOLLOWUP_LEAD_BEGIN = 'FOLLOWUP_LEAD_BEGIN';
export const FOLLOWUP_LEAD_SUCCESS = 'FOLLOWUP_LEAD_SUCCESS';
export const FOLLOWUP_LEAD_ERROR = 'FOLLOWUP_LEAD_ERROR';

export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS';
export const GET_COUNTRY_SUCCESS = 'GET_COUNTRY_SUCCESS';
export const GET_STATE_SUCCESS = 'GET_STATE_SUCCESS';
export const GET_CITY_SUCCESS = 'GET_CITY_SUCCESS';
export const GET_TYPE_OF_CUSTOMER_SUCCESS = 'GET_TYPE_OF_CUSTOMER_SUCCESS';
export const GET_TYPE_OF_INDUSTRY_SUCCESS = 'GET_TYPE_OF_INDUSTRY_SUCCESS';
export const GET_ZONE_SUCCESS = 'GET_ZONE_SUCCESS';
export const GET_SEGMENT_SUCCESS = 'GET_SEGMENT_SUCCESS';
export const GET_SOURCE_SUCCESS = 'GET_SOURCE_SUCCESS';
export const GET_STAGE_SUCCESS = 'GET_STAGE_SUCCESS';

export const ADD_LEAD_BEGIN = 'ADD_LEAD_BEGIN';
export const ADD_LEAD_SUCCESS = 'ADD_LEAD_SUCCESS';
export const ADD_LEAD_ERROR = 'ADD_LEAD_ERROR';

export const UPDATE_LEAD_BEGIN = 'UPDATE_LEAD_BEGIN';
export const UPDATE_LEAD_SUCCESS = 'UPDATE_LEAD_SUCCESS';
export const UPDATE_LEAD_ERROR = 'UPDATE_LEAD_ERROR';

export const GET_START_MEETING_BEGIN = 'GET_START_MEETING_BEGIN';
export const GET_START_MEETING_SUCCESS = 'GET_START_MEETING_SUCCESS';
export const GET_START_MEETING_ERROR = 'GET_START_MEETING_ERROR';

export const GET_END_MEETING_BEGIN = 'GET_END_MEETING_BEGIN';
export const GET_END_MEETING_SUCCESS = 'GET_END_MEETING_SUCCESS';
export const GET_END_MEETING_ERROR = 'GET_END_MEETING_ERROR';

export const CANCEL_ASSIGN_BEGIN = 'CANCEL_ASSIGN_BEGIN';
export const CANCEL_ASSIGN_SUCCESS = 'CANCEL_ASSIGN_SUCCESS';
export const CANCEL_ASSIGN_ERROR = 'UPDATE_LEAD_ERROR';

export const REMOVE_COLLABORATOR_BEGIN = 'REMOVE_COLLABORATOR_BEGIN';
export const REMOVE_COLLABORATOR_SUCCESS = 'REMOVE_COLLABORATOR_SUCCESS';
export const REMOVE_COLLABORATOR_ERROR = 'REMOVE_COLLABORATOR_ERROR';

export const CONVERT_CUSTOMER_BEGIN = 'CONVERT_CUSTOMER_BEGIN';
export const CONVERT_CUSTOMER_SUCCESS = 'CONVERT_CUSTOMER_SUCCESS';
export const CONVERT_CUSTOMER_ERROR = 'CONVERT_CUSTOMER_ERROR';
